#this role turned out a real bummer so separating tasks into 2 - crds first (annotations blow up) and argo itself later,
#as well as adding wait clauses (registering crds took time and ansible applied on top, making a real mess)
#^originally. Supposedly. Separation (url) blows up too. Adding them together with corresponding wait clauses.

- name: ensure argocd namespace exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: install argocd
  ansible.builtin.command: >
    kubectl apply -n argocd
    -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  register: argo_install
  failed_when: >
    argo_install.rc != 0 and
    "AlreadyExists" not in argo_install.stderr

- name: wait for argocd CRDs
  ansible.builtin.command: kubectl get crd applications.argoproj.io
  register: crd_check
  until: crd_check.rc == 0
  retries: 20
  delay: 3

- name: wait for argocd server deployment
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: argocd
    name: argocd-server
  register: result
  until: result.resources[0].status.readyReplicas is defined and result.resources[0].status.readyReplicas > 0
  retries: 30
  delay: 10

- name: expose argocd via nodeport
  kubernetes.core.k8s:
    state: patched
    kind: Service
    namespace: argocd
    name: argocd-server
    definition:
      spec:
        type: NodePort




