- name: install minikube package
  ansible.builtin.apt:
    deb: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
    state: present
  become: true

#ansible will end up creating /root/.minikube as part of the deb installation
#thus breaking the whole sequence. It will look /profiles, get split brain and orchestrate everything using podman (cursed)

#- name: start minikube with podman driver
#  ansible.builtin.command: minikube start --driver=podman
#  args:
#    creates: "{{ ansible_env.HOME }}/.minikube"

#- name: start minikube with podman driver
#  ansible.builtin.command: minikube start --driver=podman --force
#  become: true


- name: start minikube with podman driver
  ansible.builtin.command: minikube start --driver=podman --force
  args:
    creates: "/root/.minikube/profiles/minikube"
  become: true
