- name: pull grafana image
  containers.podman.podman_image:
    name: grafana/grafana
    tag: latest
    state: present

- name: run grafana
  containers.podman.podman_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - /opt/observability/grafana:/var/lib/grafana

