#- name: pull grafana image
#  containers.podman.podman_image:
#    name: grafana/grafana
#   tag: latest
#    state: present

#- name: run grafana
#  containers.podman.podman_container:
#    name: grafana
#    image: grafana/grafana:latest
#    state: started
#    restart_policy: always
#    ports:
#      - "3000:3000"
#    volumes:
#      - /opt/observability/grafana:/var/lib/grafana

#^botched^. Or not. Use if you want a separate grafana under podman.

#one off task for grafana, and the whole stack since they will all live in the monitoring ns

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true
  
#need the kubernetes library in python
#need pip for it as apt doesnt have it :)))))))))

- name: Install kubernetes Python package
  pip:
    name: kubernetes
    executable: pip3
  become: true
  
- name: ensure monitoring namespace exists #
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

#- name: apply kube manifests
#  kubernetes.core.k8s:
#    state: present
#    src: "{{ playbook_dir }}/../../monitoring/grafana/"
#

- name: apply grafana datasource
  kubernetes.core.k8s:
    state: present
    src: "{{ grafana_manifest_dir }}/datasource.yaml"

- name: apply grafana deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ grafana_manifest_dir }}/deployment.yaml"

- name: apply grafana service
  kubernetes.core.k8s:
    state: present
    src: "{{ grafana_manifest_dir }}/service.yaml"
