- name: Pull Grafana image
  podman_image:
    name: grafana/grafana
    tag: latest
    state: present

- name: Run Grafana
  podman_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /opt/observability/grafana:/var/lib/grafana

