- name: create observability directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
    owner: root
    group: root
  loop:
    # Base
    - { path: /opt/observability }

    # Prometheus
    - { path: /opt/observability/prometheus }
    - { path: /opt/observability/prometheus/data }
    - { path: /opt/observability/prometheus/config }

    # Grafana
    - { path: /opt/observability/grafana }
    - { path: /opt/observability/grafana/data, mode: '0775' }
    - { path: /opt/observability/grafana/provisioning }
    - { path: /opt/observability/grafana/provisioning/datasources }

    # Loki
    - { path: /opt/observability/loki }

- name: create default Prometheus config file
  ansible.builtin.copy:
    dest: /opt/observability/prometheus/config/prometheus.yml
    mode: '0644'
    owner: root
    group: root
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
  become: true

