- name: pull Loki image
  containers.podman.podman_image:
    name: grafana/loki
    tag: latest
    state: present

- name: run loki container
  containers.podman.podman_container:
    name: loki
    image: grafana/loki:latest
    state: started
    restart_policy: always
    ports:
      - "3100:3100"
    volumes:
      - /opt/observability/loki:/loki

